[package]
name = "countdown"
version = "0.0.1"
authors = ["fteychene <francois.teychene@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
log = "0.4"
simplelog = "0.9"
humantime = "2.1"
term = "0.7"